experiment_name: "grosshans_SWI_aug6_decoder-only_C"
output_base_dir: "runs"
training:
  images_dir: "/tachyon/groups/scratch/gmicro_ipa/ggrossha/ancneagu/swi_annotations/augmented/images"
  labels_dir: "/tachyon/groups/scratch/gmicro_ipa/ggrossha/ancneagu/swi_annotations/augmented/labels"
  model_type: "vit_t"
  patch_shape: [1024, 1024]
  batch_size: 6
  n_epochs: 100
  n_samples: null
  num_workers: 12
  learning_rate: 5.0e-5
  early_stopping: 20
  val_split: 0.05
  shuffle_data: true
  shuffle_seed: 42
  train_instance_segmentation_only: true
  normalize_inputs: true
  normalize_lower_percentile: 1.0
  normalize_upper_percentile: 99.5
  use_min_instance_sampler: false
  min_instances_per_patch: 1
  min_instance_size: 1
  save_validation_predictions_frequency: null
  checkpoint_name: "grosshans_SWI_aug6_C_checkpoint"
  resume_from_checkpoint: "runs/grosshans_SWI_aug6_decoder-only_C/checkpoints/grosshans_SWI_aug6_C_checkpoint/best.pt"
  export_path: "runs/SWI/grosshans_SWI_aug6_C_vit-t_model.pt"
log_level: "INFO"
