experiment_name: "grosshans_SWI_unstacked_full-sam_lr5e-5_cold"
output_base_dir: "runs"
training:
  images_dir: "/tachyon/groups/scratch/gmicro_ipa/ggrossha/ancneagu/swi_annotations/images_unstacked"
  labels_dir: "/tachyon/groups/scratch/gmicro_ipa/ggrossha/ancneagu/swi_annotations/masks_unstacked_matched"
  model_type: "vit_b_lm"
  patch_shape: [1024, 1024]
  batch_size: 6
  n_epochs: 100
  n_samples: null
  num_workers: 0
  learning_rate: 5.0e-5
  early_stopping: 30
  val_split: 0.05
  shuffle_data: true
  shuffle_seed: 42
  train_instance_segmentation_only: false
  normalize_inputs: true
  normalize_lower_percentile: 1.0
  normalize_upper_percentile: 99.5
  use_min_instance_sampler: false
  min_instances_per_patch: 1
  min_instance_size: 1
  save_validation_predictions_frequency: null
  checkpoint_name: "grosshans_SWI_unstacked_full-sam_lr5e-5_cold_ckpt"
  resume_from_checkpoint: null
  export_path: "runs/SWI/grosshans_SWI_unstacked_full-sam_lr5e-5_cold_model.pt"
log_level: "INFO"
